/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class CandidateSchema extends BaseModel {
  static $columns = ['answers', 'createdAt', 'enteredVoting2', 'id', 'roundId', 'statement', 'status', 'updatedAt', 'userId'] as const
  $columns = CandidateSchema.$columns
  @column()
  declare answers: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare enteredVoting2: boolean
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare roundId: number
  @column()
  declare statement: string | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class EmailVerificationSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'expiresAt', 'id', 'token', 'updatedAt', 'usedAt'] as const
  $columns = EmailVerificationSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare token: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column.dateTime()
  declare usedAt: DateTime | null
}

export class RoundSchema extends BaseModel {
  static $columns = ['campaignEndsAt', 'createdAt', 'endsAt', 'id', 'mode', 'month', 'special', 'startsAt', 'status', 'updatedAt', 'voting1EndsAt', 'voting2EndsAt'] as const
  $columns = RoundSchema.$columns
  @column.dateTime()
  declare campaignEndsAt: DateTime
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare endsAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare mode: string
  @column()
  declare month: string
  @column()
  declare special: boolean
  @column.dateTime()
  declare startsAt: DateTime
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column.dateTime()
  declare voting1EndsAt: DateTime | null
  @column.dateTime()
  declare voting2EndsAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'permissions', 'updatedAt', 'zulipUserId'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare permissions: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare zulipUserId: number | null
}
